public class ListExample {


/*

List<String> nms = new List<String>();
nms.add('Srinivas');
nms.add('karuna');
nms.add('Sharayu');
system.debug('=====>>>>'+ nms);
nms.add(0,'Bandi');
system.debug('=====>>>>'+ nms);



List<Integer> int0 = new List<Integer>();

int0.add(10);
int0.add(20);
List<Integer> int1 = new List<Integer>{30,40};
int0.addAll(int1);
system.debug('===>>>List Example :'+ int0);




List<Integer> int0 = new List<Integer>();

int0.add(10);
int0.add(20);
int0.add(30);
int0.add(40);
Integer a=int0.get(0);
Integer c=int0.get(2);
system.debug('====>>>> :'+ a);
system.debug('====>>>> :'+ c);





List<Integer> int0 = new List<Integer>();

int0.add(10);
int0.add(20);
int0.add(30);
int0.add(40);
List<Integer> int01 = new List<Integer>();

int01.add(10);
int01.add(20);
int01.add(30);
int01.add(40);
Boolean b=int0.equals(int01);
system.debug('=====>>>>> Result :'+b);




List<Integer> int0 = new List<Integer>();

int0.add(10);
int0.add(20);
int0.add(30);
int0.add(40);
List<Integer> int01 = new List<Integer>();

int01.add(10);
int01.add(20);
int01.add(30);
int01.add(40);
Boolean b=int0.isEmpty();
system.debug('=====>>>>> Result :'+b);

List<Integer> int0 = new List<Integer>();

int0.add(10);
int0.add(20);
int0.add(30);
int0.add(40);
List<Integer> int01 = new List<Integer>();

int01.add(10);
int01.add(20);
int01.add(30);
int01.add(40);
Integer b=int0.size();
system.debug('=====>>>>> Result :'+b);

*/



}