public class OpportunitiesPaginationController {
    Public Integer size{get; set;}
    Public Integer noOfRecords{get; set;}
    Public List<SelectOption> paginationSizeOptions{get; set;}
    
    public OpportunitiesPaginationController(){
        size = 10;
        paginationSizeOptions = new List<SelectOption>();
        paginationSizeOptions.add(new SelectOption('5','5'));
        paginationSizeOptions.add(new SelectOption('10','10'));
        paginationSizeOptions.add(new SelectOption('20','20'));
        paginationSizeOptions.add(new SelectOption('50','50'));
        paginationSizeOptions.add(new SelectOption('100','100'));
    }
    public ApexPages.StandardSetController setCon{
        get{
            if(setCon ==null){
                setCon = New ApexPages.StandardSetController(Database.getQueryLocator([SELECT
                    id,Name,AccountId,Account.name,Amount,StageName,CloseDate,LastModifiedDate from Opportunity]));
                setCon.setPageSize(size);
                noOfRecords = setCon.getResultsize();
            }
            return setCon;
        }
        set;
    }
        //Change the size of pagination
        public PageReference refreshPageSize(){
            setCon.setPageSize(size);
            return null;
        }
        //Initialize setcon and return a list of recirds
        public List<Opportunity> getOpportunities(){
            return(List<Opportunity>) setCon.getRecords();
        }
        
    }