public class SetExample {
/*

List<Integer> int0 = new List<Integer>();

int0.add(10);
int0.add(20);
int0.add(30);
int0.add(40);
int0.add(10);
int0.add(20);
system.debug('=====>>>>>List Result :'+int0);

Set<Integer> int10 = new Set<Integer>();
int10.add(10);
int10.add(20);
int10.add(30);
int10.add(40);
int10.add(10);
int10.add(20);
system.debug('=====>>>>>Set Result :'+int10);



Set<Integer> int0 = new Set<Integer>();

int0.add(10);
int0.add(20);
int0.add(30);
int0.add(40);
Boolean b=int0.contains(60);
system.debug('=====>>>>>List Result :'+b);


Set<Integer> int0 = new Set<Integer>();

int0.add(10);
int0.add(20);
int0.add(30);
int0.add(40);
List<Integer>int1 = new List<Integer>{10,20};
Boolean b=int0.containsall(int1);
system.debug('=====>>>>>List Result :'+b);

*/




}